### ISSUE TITLE
[Meta] Achieve Size Parity with Gzip + Minify

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#85]
**Objective** Achieve size parity for the Facebook sample set with gzipped files. This is for files without laziness. We are willing to accept a modest increase of size with files compiled with Skippable nodes.

At the time of this measure, applying binjs_encode + gzip on the Facebook minified fileset produces a result that is ~14% larger than just gzip.

This is down from ~25% since #82, but it's still too large.

Interestingly, before gzip, our files are ~35% *smaller* than the Facebook minified fileset. So, clearly, our format is not as compressible as text.

Possible avenues:

- Get rid of data that is not actually useful
    - [X] Rework lazy lists, replace them with `Skippable` #82
    - [X] Get rid of field names in headers #61
- Reorganize data to make it easier to compress.
- Perform some compression that is easier for us than for e.g. gzip.
    - [ ] Find a way to semi-automatically transform a grammar to insert Zero, One, etc. #77
    - [ ] Pack successive booleans #62
    - [ ] Optimize strings that appear only once #44
    - [ ] Optimize storage of numbers #24
- Generally, experiment to get some data.
    - [X] Find out which files have the worst compression with binjs #43
    - [X] Investigate having ZeroLiteral and OneLiteral #28 
    - [X] Investigate having LiteralTrueExpression and LiteralFalseExpression #27 
    - [X] Consider namespacing enumerations #37
    - [ ] Consider a size/speed optimization for simple `ObjectLiteral`. #45
    - [ ] Check compression without AssertedScope. #102 
    - [X] Test compression with NUL-terminated strings #103 
    - [ ] Test `varnum` for `capturedNames` #104
    - [ ] Test inline `capturedNames` #105
    - [X] Test different sortings for `[STRINGS]` #106 
    - [X] Experiment with compression size if we remove the `[GRAMMAR]` section #107
    - [ ] Let's inline `hasDirectEval` in `Asserted*Scope` #108
    - [ ] Consider De Bruijn indices, once again #109

# Relevant data

- [Compression results on various frameworks](https://gist.github.com/Yoric/dc6706b5bd3fe7dd988561a75c7d3a70), sorted by best-to-rust gzip ratio.
- [Worst offenders](https://github.com/binast/binjs-ref/issues/43#issuecomment-382629165)

**Comment by Yoric** [comment]
**Update** When we concatenate the entire 42Mb of JS, the gzipped-compressed .binjs is 0.94 of the gzipped-compressed .js .

**Comment by dominiccooney** [comment]
I started to take a look at this but binjs-ref seems busted for me at fd20e14723202ede82e59bc8ed19188a50cd7bd0; I ran `cargo run --bin binjs_encode -- --help` but it snapped at me:

````
   Compiling binjs_meta v0.3.6 (file:///Users/dpc/stuff/binast-sizes/binjs-ref/c$
error[E0658]: `impl Trait` in return position is experimental (see issue #34511) 
   --> crates/binjs_meta/src/util.rs:423:31                                      
    |                                                                            
423 |         pub fn iter(&self) -> impl Iterator<Item = (usize, &Node<T>)> {    
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |                                  
    |                                         |                                  
    | error: aborting due to previous error   |                                  
    |                                         |                                  
    | error: Could not compile `binjs_meta`.  |                                  
    |                                         |                
````

**Comment by Yoric** [comment]
@dominiccooney Do you have Rust Nightly?

**Comment by Yoric** [comment]
I just tested on some of the most popular frameworks: https://gist.github.com/Yoric/8bd214a401f056892afd2c423549aef2.

**Comment by Yoric** [comment]
Attaching a few samples.

[frameworks.zip](https://github.com/binast/binjs-ref/files/1979985/frameworks.zip)

**Comment by Yoric** [comment]
This was resolved a few months ago, without us realizing!
